### ISSUE TITLE
It seems to fail access sandbox

### ISSUE THREAD

**Issue by Kernelzero** [developerinsider/Sign-In-with-Apple-Demo#3]
`SignInWithAppleDemo[24074:4746867] libMobileGestalt MobileGestaltSupport.m:121: pid 24074 (SignInWithAppleDemo) does not have sandbox access for re6Zb+zwFKJNlkQTUeT+/w and IS NOT appropriately entitled`

what is it? how to solve it?

**Comment by vineetchoudhary** [comment]
Hi @Kernelzero, Please check this thread ~ https://forums.developer.apple.com/thread/125178#393532

**Comment by Kernelzero** [comment]
really appreciate you~
